---

- hosts: webservers
  become: yes
  remote_user: ansible
  gather_facts: yes
  vars:
    service_target: httpd
    service_state: started
  tasks:
    - name: ensure service is running 
      service:
        name: "{{ service_target }}"
        state: "{{ service_state }}"
    
